// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfwczsoclliysgepkwsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indmd2N6c29jbGxpeXNnZXBrd3NxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4NjQ1MjcsImV4cCI6MjA1NzQ0MDUyN30.PoszWWrvlk6G_GmRQ_IGASEDAqKgoUWObQ070XZWgy4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);